################################################################################
#                                                                              #
#                                 Human Resources                              #
#                                                                              #
################################################################################
swagger: '2.0'

info:
  version: "0.2.0"
  title: Human Resources API

produces:
  - application/json
consumes:
  - application/json

################################################################################
#                                                                              #
#                                 ToDo/Questions                               #
#                                                                              #
################################################################################
#
# 1. Look into including additional parameters/filters
# 2. Add security and authentication (checkout Instagram's api example)
#
################################################################################
#                                                                              #
#                                 Paths                                        #
#                                                                              #
################################################################################
paths:
#                                                                              #
#                                 /employees                                   #
#                                                                              #
  /employee:
    get:
      operationId: controllers.employees.get
      description:
        Gets a list of of all of the employees or a single employee currently in the system
      parameters:
        - $ref: "#/parameters/employee_id"
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              employee_array:
                type: array
                items:
                  $ref: "#/definitions/Employee"
        default:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/Error"
    post:
      operationId: controllers.employees.post
      description:
        Adds a single employee into the system
      parameters:
        - name: employee
          in: body
          schema:
            $ref: "#/definitions/EmployeePost"
          required: true
          description:
            This is an Employee object that can only post information that can be modified.
            This is similar to patching, but requires that the employee to not currently exist in the system yet.
      responses:
        204:
          description: Employee created!
        400:
          description: Employee could not be created.
        default:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/Error"
    patch:
      operationId: controllers.employees.patch
      description:
        Changes the information of a single employee
      parameters:
        - name: employee
          in: body
          schema:
            $ref: "#/definitions/EmployeePatch"
          required: true
          description:
            This is a partial or full Employee object that describes what information needs to be changed
            for a particular employee. This is similar to posting but does not require the full object.
      responses:
        200:
          description: Employee information found and changed
        default:
          description: Employee either not found or

    delete:
      operationId: controllers.employees.delete
      description:
        Deletes a single employee
      parameters:
        - name: employee_id
          in: query
          type: integer
          required: true
          description: The employee id by which to look up the appropriate Employee object to delete.
      responses:
        200:
          description: Employee deleted
        default:
          description: Employee not deleted


  /employee/{employee_id}:
    get:
      operationId: controllers.employee.get
      description:
        A single employee currently in the system
      parameters:
        - name: employee_id
          in: path
          type: integer
          required: true
          description: The employee id by which to look up the appropriate Employee object to delete.
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              employee_array:
                type: array
                items:
                  $ref: "#/definitions/Employee"
        default:
          description: Unexpected Error
          schema:
            $ref: "#/definitions/Error"

################################################################################
#                                                                              #
#                                 Definitions                                  #
#                                                                              #
################################################################################

definitions:
#                                                                              #
#                                 Employee                                     #
#                                                                              #
  Employee:
    type: object
    properties:
      is_active:
        type: boolean
      employee_id:
        type: integer
      fname:
        type: string
      lname:
        type: string
      birth_date:
        type: string
        format: date_time
      address:
        type: string
        pattern: '^[\d]+[\s[a-zA-Z/.\u00C0-\u017F]+,[\s[a-zA-Z\u00C0-\u017F]+,[\s[a-zA-Z\u00C0-\u017F]+\s[\d]+$'
        description: Accepts standard full addresses e.g. 1111 blank st., New York, New York 11217
      department:
        type: string
      role:
        type: string
      team_start_date:
        type: string
        format: date_time
      start_date:
        type: string
        format: date_time
      salary:
        type: integer

#                                                                              #
#                                 EmployeePost                                 #
#                                                                              #
  EmployeePost:
    required:
      - is_active
      - fname
      - lname
      - birth_date
      - address
      - department
      - role
      - start_date
    type: object
    properties:
      is_active:
        type: boolean
      fname:
        type: string
      lname:
        type: string
      birth_date:
        type: string
        format: date
      address:
        type: string
        pattern: '^[\d]+[\s[a-zA-Z/.\u00C0-\u017F]+,[\s[a-zA-Z\u00C0-\u017F]+,[\s[a-zA-Z\u00C0-\u017F]+\s[\d]+$'
        description: Accepts standard full addresses e.g. 1111 blank st., New York, New York 11217
      department:
        type: string
      role:
        type: string
      start_date:
        type: string
        format: date

#                                                                              #
#                                 EmployeePatch                                #
#                                                                              #
  EmployeePatch:
    required:
      - employee_id
    type: object
    properties:
      is_active:
        type: boolean
      employee_id:
        type: integer
      fname:
        type: string
      lname:
        type: string
      birth_date:
        type: string
        format: date
      address:
        type: string
        pattern: '^[\d]+[\s[a-zA-Z/.\u00C0-\u017F]+,[\s[a-zA-Z\u00C0-\u017F]+,[\s[a-zA-Z\u00C0-\u017F]+\s[\d]+$'
        description: Accepts standard full addresses e.g. 1111 blank st., New York, New York 11217
      department:
        type: string
      role:
        type: string
      department_start_date:
        type: string
        format: date
      start_date:
        type: string
        format: date
      salary:
        type: integer
      username:
        type: string
      password:
        type: string

#                                                                              #
#                                 Error                                        #
#                                                                              #
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string

################################################################################
#                                                                              #
#                                 Parameters                                   #
#                                                                              #
################################################################################
parameters:
  employee_id:
    name: employee_id
    in: query
    type: array
    items:
      type: integer
    required: false
    description: id of a particular employee or set of employees

